version: '3.8'

services:
  # Сервер (бэкенд)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lawtech-server
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-5000}:5000"
    environment:
      - GIGACHAT_AUTH_KEY=${GIGACHAT_AUTH_KEY:-ZjFmODc3YWYtMzMzMC00ZWI5LTlmZTYtZjQ5ODYxM2YwZjM3OjQzOWVlY2UzLTAxMjYtNDVkMy1iOWQ3LTg3OTI3M2NjMzI0Mw==}
      - GIGACHAT_SCOPE=${GIGACHAT_SCOPE:-GIGACHAT_API_PERS}
      - JWT_SECRET=${JWT_SECRET:-law-tech-secret-key}
      - OCR_API_KEY=${OCR_API_KEY:-K89514712488957}
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - lawtech-network

  # Фронтенд
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lawtech-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-/api}
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      - server
    networks:
      - lawtech-network
    links:
      - server

# Определение общей сети для контейнеров
networks:
  lawtech-network:
    driver: bridge 