version: '3'

services:
  # Сервер (бэкенд)
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - faiss-service
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FAISS_SERVICE_URL=http://faiss-service:5000

  # Фронтенд
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  faiss-service:
    build:
      context: ./server/scripts
      dockerfile: Dockerfile.faiss
    ports:
      - "5000:5000"
    volumes:
      - ./server/scripts:/app
      - ./server/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

# Определение общей сети для контейнеров
networks:
  lawtech-network:
    driver: bridge 