services:
  # Backend API service
  - type: web
    name: lawtech-server
    env: node
    plan: free
    rootDir: ./server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        value: law-tech-secret-key
      - key: NODE_ENV
        value: production

  # Frontend static site
  - type: static
    name: lawtech-frontend
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://lawtech-server.onrender.com/api