CREATE TABLE IF NOT EXISTS consultation_analysis (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 consultation_id INT NOT NULL,
 office_id INT NOT NULL,
 employee_id INT DEFAULT NULL,
 source_id INT DEFAULT NULL,
 topic VARCHAR(255) DEFAULT NULL,
 lead_quality ENUM('HIGH','MEDIUM','LOW','ECONOMICALLY_UNVIABLE','NOT_LEGALLY_SOLVABLE','UNKNOWN') NOT NULL,
 commercial_potential ENUM('HIGH','MEDIUM','LOW','NONE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
 service_fit ENUM('YES','PARTIAL','NO','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
 legally_solvable ENUM('YES','PARTIAL','NO','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
 need_identified ENUM('YES','PARTIAL','NO','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
 decision_maker_identified ENUM('YES','NO','NA','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
 solution_understood ENUM('YES','PARTIAL','NO','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
 offer_made ENUM('YES','NO','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
 objection_identified ENUM('YES','NO','NONE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
 objection_processed ENUM('YES','PARTIAL','NO','NONE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
 proposed_service VARCHAR(255) DEFAULT NULL,
 proposed_price DECIMAL(15,2) DEFAULT NULL,
 next_step ENUM('FOLLOW_UP','PROPOSAL_SENT','CLIENT_DECLINED','NOT_FIXED') NOT NULL DEFAULT 'NOT_FIXED',
 loss_category ENUM('LEAD_QUALITY','SALES_PROCESS','CLIENT_DELAY','SERVICE_PROBLEM','NON_TARGET','UNRESOLVED','OTHER') NOT NULL,
 loss_reason VARCHAR(80) NOT NULL,
 manager_comment TEXT DEFAULT NULL,
 evidence_sources JSON NOT NULL,
 data_sufficiency ENUM('SUFFICIENT','PARTIAL','INSUFFICIENT') NOT NULL,
 missing_data_reason VARCHAR(255) DEFAULT NULL,
 classification_basis ENUM('FACTS','MIXED','HYPOTHESIS') NOT NULL DEFAULT 'MIXED',
 confidence_score TINYINT UNSIGNED NOT NULL DEFAULT 0,
 ai_category VARCHAR(50) DEFAULT NULL,
 ai_confidence DECIMAL(5,2) DEFAULT NULL,
 ai_analysis JSON DEFAULT NULL,
 created_by INT NOT NULL,
 updated_by INT NOT NULL,
 version INT NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 deleted_at DATETIME DEFAULT NULL,
 deleted_by INT DEFAULT NULL,
 PRIMARY KEY(id),
 UNIQUE KEY uq_consultation_analysis(consultation_id),
 KEY idx_ca_office_created(office_id,created_at),
 KEY idx_ca_employee_created(employee_id,created_at),
 KEY idx_ca_source_created(source_id,created_at),
 KEY idx_ca_category_created(loss_category,created_at),
 CONSTRAINT fk_ca_consultation FOREIGN KEY(consultation_id) REFERENCES appointments(id) ON DELETE CASCADE,
 CONSTRAINT fk_ca_office FOREIGN KEY(office_id) REFERENCES offices(id) ON DELETE CASCADE,
 CONSTRAINT fk_ca_employee FOREIGN KEY(employee_id) REFERENCES users(id) ON DELETE SET NULL,
 CONSTRAINT fk_ca_source FOREIGN KEY(source_id) REFERENCES appointment_sources(id) ON DELETE SET NULL,
 CONSTRAINT fk_ca_created_by FOREIGN KEY(created_by) REFERENCES users(id),
 CONSTRAINT fk_ca_updated_by FOREIGN KEY(updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS consultation_analysis_history (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 analysis_id BIGINT UNSIGNED NOT NULL,
 consultation_id INT NOT NULL,
 office_id INT NOT NULL,
 version INT NOT NULL,
 action ENUM('CREATE','UPDATE','DELETE') NOT NULL,
 old_values JSON DEFAULT NULL,
 new_values JSON DEFAULT NULL,
 changed_by INT NOT NULL,
 changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(id),
 KEY idx_cah_analysis(analysis_id,version),
 KEY idx_cah_office_date(office_id,changed_at),
 CONSTRAINT fk_cah_analysis FOREIGN KEY(analysis_id) REFERENCES consultation_analysis(id) ON DELETE CASCADE,
 CONSTRAINT fk_cah_changed_by FOREIGN KEY(changed_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS consultation_analysis_settings (
 office_id INT NOT NULL,
 min_sample_size INT NOT NULL DEFAULT 20,
 coverage_warning_pct DECIMAL(5,2) NOT NULL DEFAULT 70.00,
 revenue_method ENUM('TOPIC_AVG','OFFICE_AVG') NOT NULL DEFAULT 'TOPIC_AVG',
 updated_by INT DEFAULT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(office_id),
 CONSTRAINT fk_cas_office FOREIGN KEY(office_id) REFERENCES offices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
