SET @c=(SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='consultation_analysis' AND COLUMN_NAME='client_objection');
SET @q=IF(@c=0,"ALTER TABLE consultation_analysis ADD COLUMN client_objection TEXT NULL AFTER objection_processed","SELECT 1");PREPARE x FROM @q;EXECUTE x;DEALLOCATE PREPARE x;
SET @analysis_status_missing=(SELECT COUNT(*)=0 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='consultation_analysis' AND COLUMN_NAME='analysis_status');
SET @q=IF(@analysis_status_missing,"ALTER TABLE consultation_analysis ADD COLUMN analysis_status ENUM('DRAFT','QUEUED','PROCESSING','READY_FOR_REVIEW','CONFIRMED','CORRECTED','FAILED','STALE') NOT NULL DEFAULT 'DRAFT' AFTER confidence_score","SELECT 1");PREPARE x FROM @q;EXECUTE x;DEALLOCATE PREPARE x;
SET @q=IF(@analysis_status_missing,"UPDATE consultation_analysis SET analysis_status='CONFIRMED' WHERE deleted_at IS NULL","SELECT 1");PREPARE x FROM @q;EXECUTE x;DEALLOCATE PREPARE x;
SET @c=(SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='consultation_analysis' AND COLUMN_NAME='probable_reason');
SET @q=IF(@c=0,"ALTER TABLE consultation_analysis ADD COLUMN probable_reason VARCHAR(500) NULL AFTER ai_confidence, ADD COLUMN probable_need VARCHAR(500) NULL AFTER probable_reason, ADD COLUMN ai_summary TEXT NULL AFTER probable_need, ADD COLUMN ai_evidence JSON NULL AFTER ai_summary, ADD COLUMN ai_contradictions JSON NULL AFTER ai_evidence, ADD COLUMN ai_missing_data JSON NULL AFTER ai_contradictions, ADD COLUMN model_version VARCHAR(100) NULL AFTER ai_missing_data, ADD COLUMN prompt_version VARCHAR(50) NULL AFTER model_version, ADD COLUMN input_hash CHAR(64) NULL AFTER prompt_version, ADD COLUMN confirmed_by INT NULL AFTER input_hash, ADD COLUMN confirmed_at DATETIME NULL AFTER confirmed_by","SELECT 1");PREPARE x FROM @q;EXECUTE x;DEALLOCATE PREPARE x;
SET @c=(SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='consultation_analysis_settings' AND COLUMN_NAME='analysis_enabled');
SET @q=IF(@c=0,"ALTER TABLE consultation_analysis_settings ADD COLUMN analysis_enabled TINYINT(1) NOT NULL DEFAULT 1, ADD COLUMN ai_enabled TINYINT(1) NOT NULL DEFAULT 0","SELECT 1");PREPARE x FROM @q;EXECUTE x;DEALLOCATE PREPARE x;
CREATE TABLE IF NOT EXISTS consultation_analysis_versions (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,analysis_id BIGINT UNSIGNED NOT NULL,version INT NOT NULL,input_snapshot JSON NOT NULL,ai_result JSON NULL,status VARCHAR(32) NOT NULL,model_version VARCHAR(100) NULL,prompt_version VARCHAR(50) NULL,error_code VARCHAR(80) NULL,created_by INT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at DATETIME NULL,
 PRIMARY KEY(id),UNIQUE KEY uq_ca_version(analysis_id,version),KEY idx_cav_status(status),CONSTRAINT fk_cav_analysis FOREIGN KEY(analysis_id) REFERENCES consultation_analysis(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
