import React,{useEffect,useState} from 'react';
import {Modal,Select,Input,InputNumber,Radio,Alert,App,Space,Tag} from 'antd';
import {apiInstance} from '../shared/api/instance';

type Props={open:boolean;consultation:any;onClose:()=>void;onSaved:()=>void};
const YPN=[{value:'YES',label:'Да'},{value:'PARTIAL',label:'Частично'},{value:'NO',label:'Нет'},{value:'UNKNOWN',label:'Невозможно определить'}];
const REASONS=[
 ['CLIENT_DELAY','NEED_THINK','Нужно подумать'],['CLIENT_DELAY','CONSULT_OTHERS','Нужно посоветоваться'],['CLIENT_DELAY','NOT_READY','Не готов принять решение'],['CLIENT_DELAY','RETURN_LATER','Вернётся позже'],
 ['SERVICE_PROBLEM','PRICE','Стоимость услуги'],['SERVICE_PROBLEM','NO_MONEY_NOW','Нет денег сейчас'],['SERVICE_PROBLEM','PAYMENT_SCHEME','Не устраивает схема оплаты'],['SERVICE_PROBLEM','CONDITIONS','Не устроили условия'],['SERVICE_PROBLEM','SERVICE_SCOPE','Не устроил объём услуги'],['SERVICE_PROBLEM','VALUE_NOT_CLEAR','Не понял ценность'],
 ['SALES_PROCESS','NEED_NOT_IDENTIFIED','Не выявлена потребность'],['SALES_PROCESS','SOLUTION_NOT_CLEAR','Клиент не понял решение'],['SALES_PROCESS','VALUE_NOT_FORMED','Не сформирована ценность'],['SALES_PROCESS','OBJECTION_NOT_HANDLED','Не отработано возражение'],['SALES_PROCESS','OFFER_NOT_MADE','Договор не предложен'],
 ['LEAD_QUALITY','LOW_POTENTIAL','Низкая перспективность'],['LEAD_QUALITY','ECONOMICALLY_UNVIABLE','Экономически нецелесообразно'],['LEAD_QUALITY','NO_SUPPORT_NEEDED','Сопровождение не требуется'],['LEAD_QUALITY','NOT_LEGALLY_SOLVABLE','Вопрос не решается юридически'],
 ['NON_TARGET','NON_TARGET_SERVICE','Нецелевая услуга'],['NON_TARGET','OUT_OF_PROFILE','Не соответствует профилю'],['OTHER','OTHER','Иная причина'],['UNRESOLVED','INSUFFICIENT_DATA','Недостаточно данных']
];
const initial:any={lead_quality:'UNKNOWN',commercial_potential:'UNKNOWN',service_fit:'UNKNOWN',legally_solvable:'UNKNOWN',need_identified:'UNKNOWN',decision_maker_identified:'UNKNOWN',solution_understood:'UNKNOWN',offer_made:'UNKNOWN',objection_identified:'UNKNOWN',objection_processed:'UNKNOWN',next_step:'NOT_FIXED',loss_category:'UNRESOLVED',loss_reason:'INSUFFICIENT_DATA',evidence_sources:['CRM'],data_sufficiency:'INSUFFICIENT',missing_data_reason:'Причина отказа не зафиксирована',classification_basis:'MIXED',confidence_score:30,version:0};
const ConsultationAnalysisModal:React.FC<Props>=({open,consultation,onClose,onSaved})=>{const {message}=App.useApp();const [f,setF]=useState<any>(initial);const [loading,setLoading]=useState(false);
 useEffect(()=>{if(!open||!consultation)return;(async()=>{setLoading(true);try{const r=await apiInstance.get(`/consultation-analysis/${consultation.id}`);setF(r.data.data?{...initial,...r.data.data,evidence_sources:typeof r.data.data.evidence_sources==='string'?JSON.parse(r.data.data.evidence_sources):r.data.data.evidence_sources}:{...initial,employee_id:consultation.assigned_lawyer_id,source_id:consultation.source_id,topic:consultation.comment});}catch{message.error('Не удалось загрузить разбор')}finally{setLoading(false)}})()},[open,consultation]);
 const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));const chooseReason=(v:string)=>{const r=REASONS.find(x=>x[1]===v);setF((x:any)=>({...x,loss_reason:v,loss_category:r?.[0]}))};
 const save=async()=>{setLoading(true);try{await apiInstance.put(`/consultation-analysis/${consultation.id}`,f);message.success('Разбор сохранён');onSaved();onClose();}catch(e:any){if(e?.response?.status===409){message.warning('Запись уже изменена другим руководителем. Откройте её повторно.')}else message.error(e?.response?.data?.message||'Не удалось сохранить')}finally{setLoading(false)}};
 return <Modal title="Разбор консультации" open={open} onCancel={onClose} onOk={save} okText="Сохранить разбор" cancelText="Отмена" confirmLoading={loading} width={760} destroyOnClose>
  {consultation&&<><Alert type="info" showIcon message={`${consultation.client_name} · ${consultation.source||'Без источника'} · ${consultation.assigned_lawyer_name||'Юрист не назначен'}`} description={`${consultation.appointment_date} ${consultation.appointment_time} · договор не заключён`} />
  <div className="ca-form">
   <label><span>Источник сведений</span><Select mode="multiple" value={f.evidence_sources} onChange={v=>set('evidence_sources',v)} options={['CRM','ADMIN_COMMENT','LAWYER_INFO','CLIENT_FEEDBACK','DOCUMENTS','MANAGER_PRESENT','OTHER'].map(v=>({value:v,label:{CRM:'Данные CRM',ADMIN_COMMENT:'Комментарий администратора',LAWYER_INFO:'Информация от юриста',CLIENT_FEEDBACK:'Сообщение клиента',DOCUMENTS:'Документы / переписка',MANAGER_PRESENT:'Личное присутствие',OTHER:'Иное'}[v]}))}/></label>
   <label><span>Достаточность данных</span><Radio.Group value={f.data_sufficiency} onChange={e=>set('data_sufficiency',e.target.value)} options={[{value:'SUFFICIENT',label:'Достаточно'},{value:'PARTIAL',label:'Частично'},{value:'INSUFFICIENT',label:'Недостаточно'}]}/></label>
   {f.data_sufficiency==='INSUFFICIENT'&&<label><span>Чего не хватает</span><Input value={f.missing_data_reason} onChange={e=>set('missing_data_reason',e.target.value)}/></label>}
   <label><span>Перспективность обращения</span><Select value={f.lead_quality} onChange={v=>set('lead_quality',v)} options={[['HIGH','Высокая'],['MEDIUM','Средняя'],['LOW','Низкая'],['ECONOMICALLY_UNVIABLE','Экономически нецелесообразно'],['NOT_LEGALLY_SOLVABLE','Не решается юридически'],['UNKNOWN','Невозможно определить']].map(x=>({value:x[0],label:x[1]}))}/></label>
   {[['need_identified','Потребность выявлена'],['solution_understood','Клиент понял решение'],['offer_made','Договор предложен'],['objection_identified','Возражение выявлено'],['objection_processed','Возражение отработано']].map(([k,l])=><label key={k}><span>{l}</span><Select value={f[k]} onChange={v=>set(k,v)} options={YPN}/></label>)}
   <label><span>Причина незаключения</span><Select showSearch optionFilterProp="label" value={f.loss_reason} onChange={chooseReason} options={REASONS.map(x=>({value:x[1],label:x[2]}))}/></label>
   <label><span>Основная категория</span><Select value={f.loss_category} onChange={v=>set('loss_category',v)} options={[['LEAD_QUALITY','Качество / перспективность'],['SALES_PROCESS','Процесс продажи'],['CLIENT_DELAY','Отложенное решение'],['SERVICE_PROBLEM','Предложение / услуга'],['NON_TARGET','Нецелевое обращение'],['UNRESOLVED','Недостаточно данных'],['OTHER','Прочее']].map(x=>({value:x[0],label:x[1]}))}/></label>
   <label><span>Предложенная услуга</span><Input value={f.proposed_service} onChange={e=>set('proposed_service',e.target.value)}/></label><label><span>Предложенная цена</span><InputNumber min={0} style={{width:'100%'}} value={f.proposed_price} onChange={v=>set('proposed_price',v)}/></label>
   <label className="ca-wide"><span>Комментарий руководителя</span><Input.TextArea rows={2} maxLength={1000} value={f.manager_comment} onChange={e=>set('manager_comment',e.target.value)}/></label>
   <div className="ca-wide"><Space><Tag color={f.loss_category==='SALES_PROCESS'?'red':'blue'}>{f.loss_category}</Tag><span style={{color:'var(--color-muted)'}}>Уверенность</span><InputNumber min={0} max={100} value={f.confidence_score} onChange={v=>set('confidence_score',v)}/><span>%</span></Space></div>
  </div></>}
 </Modal>};
export default ConsultationAnalysisModal;
