FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY faiss_service.py .

# Создаем директорию для данных
RUN mkdir -p /app/data

# Устанавливаем рабочую директорию
EXPOSE 5000

CMD ["python", "faiss_service.py"] 