const fs=require('fs'),db=require('../db');
const P=JSON.parse(fs.readFileSync('/app/scripts/kemerovo_migration_package_v2.json','utf8'));
const OFFICE=27, ADMIN=75, DIRECTOR=71;
const norm=s=>String(s||'').toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9]/g,'');
const parts=s=>String(s||'').replace(/\\/g,'/').split(/[\/,]/).map(x=>x.trim()).filter(x=>x&&!['дс','-','-----'].includes(norm(x)));
const iso=d=>/^\d{4}-\d{2}-\d{2}$/.test(String(d||''))?d:'2024-03-11';
const zero={cash:0,noncash:0,bank:0};
async function main(){const c=await db.getClient();try{
 const [[office]]=await c.query('SELECT * FROM offices WHERE id=? AND name=?',[OFFICE,P.meta.office]);if(!office)throw Error('Target office mismatch');
 await c.beginTransaction();
 const [old]=await c.query('SELECT id FROM contracts WHERE office_id=?',[OFFICE]);const ids=old.map(x=>x.id);
 await c.query('DELETE FROM appointments WHERE office_id=?',[OFFICE]);await c.query('DELETE FROM cash_register WHERE office_id=?',[OFFICE]);await c.query('DELETE FROM salary_payments WHERE office_id=?',[OFFICE]);await c.query('DELETE FROM expenses WHERE office_id=?',[OFFICE]);await c.query('DELETE FROM office_income WHERE office_id=?',[OFFICE]);await c.query('DELETE FROM office_balance_opening WHERE office_id=?',[OFFICE]);
 if(ids.length){const q=ids.map(()=>'?').join(',');for(const t of ['notifications','contract_history','contract_assignments','contract_payment_installments','contract_payments','acts']){try{await c.query(`DELETE FROM ${t} WHERE contract_id IN (${q})`,ids)}catch(e){if(e.code!=='ER_NO_SUCH_TABLE')throw e}}try{await c.query(`UPDATE materials SET contract_id=NULL,act_id=NULL WHERE contract_id IN (${q})`,ids)}catch{}await c.query(`DELETE FROM contracts WHERE id IN (${q})`,ids)}
 await c.query('DELETE FROM clients WHERE office_id=?',[OFFICE]);
 const [emps]=await c.query('SELECT * FROM employees WHERE office_id=? AND deleted_at IS NULL',[OFFICE]);const em=new Map();
 for(const e of emps){em.set(norm(e.last_name),e);em.set(norm(`${e.last_name}${e.first_name}`),e);em.set(norm(`${e.first_name}${e.last_name}`),e)}
 async function employee(raw,pos='Исторический сотрудник'){for(const x of parts(raw)){let e=em.get(norm(x))||em.get(norm(x.split(/\s+/)[0]));if(e)return e}const label=parts(raw)[0]||'Не указан';const toks=label.split(/\s+/);const last=toks[0].slice(0,100),first=(toks.slice(1).join(' ')||'Исторический').slice(0,100);const [r]=await c.query('INSERT INTO employees(user_id,first_name,last_name,position,office_id) VALUES(NULL,?,?,?,?)',[first,last,pos,OFFICE]);const e={id:r.insertId,user_id:null,last_name:last,first_name:first};em.set(norm(label),e);em.set(norm(last),e);return e}
 const allRefs=[...P.contracts];for(const k of ['unknown_acts','unknown_representatives','unknown_cash'])for(const r of P.exceptions[k])if(!allRefs.some(x=>x.contract_number===r.contract_number))allRefs.push({contract_number:r.contract_number,client_name:r.client_name,contract_date:r.date||r.handoff_date,lawyer_raw:r.lawyer_raw,department_raw:r.service||'Историческая запись',amount:r.amount||r.cash+r.noncash+r.bank||0,advance:0,remainder:0,phones:[],synthetic:true});
 const phoneBy=new Map();for(const x of P.contracts)phoneBy.set(x.contract_number,x.phones||[]);
 const clients=new Map();async function client(name,phones=[]){const k=norm(name)||'unknown';if(clients.has(k))return clients.get(k);const [r]=await c.query("INSERT INTO clients(name,phone,office_id,status,notes) VALUES(?,?,?,'active',?)",[name||'Неизвестный клиент',(phones[0]||''),OFFICE,phones.length>1?`Доп. телефоны: ${phones.slice(1).join(', ')}`:'Импорт Google Sheets']);clients.set(k,r.insertId);return r.insertId}
 const numberCount={},map=new Map();let contractN=0;
 for(const x of allRefs){const n=x.contract_number;numberCount[n]=(numberCount[n]||0)+1;const actual=numberCount[n]>1?`${n}-${numberCount[n]}`:n;const cid=await client(x.client_name,x.phones||phoneBy.get(n)||[]);const law=await employee(x.lawyer_raw||'Не указан','Юрист (исторический)');const type=/представ/i.test(x.department_raw||'')?'court_rep':'docs';const amount=Number(x.amount||0);const [r]=await c.query(`INSERT INTO contracts(id_client,id_employee,contract_type,docs_status,contract_date,amount,paid_amount,status,title,description,office_id,contract_number,registered_by,signed_by,payment_method,needs_lawyer_input) VALUES(?,?,?,'pending',?,?,0,'registered',?,?,?, ?,?,?, 'cash',0)`,[cid,law.id,type,iso(x.contract_date),amount,x.department_raw||null,`Импорт Google Sheets${x.synthetic?'; создан по связанной записи':''}`,OFFICE,actual,ADMIN,law.user_id||ADMIN]);if(!map.has(n))map.set(n,r.insertId);contractN++}
 const allCash=[...P.cash_entries,...P.exceptions.unknown_cash];let payN=0,cashN=0;
 for(const x of allCash){const id=map.get(x.contract_number);if(!id)continue;const law=await employee(x.lawyer_raw||'Не указан');for(const [method,amt] of [['cash',x.cash],['noncash',x.noncash],['bank',x.bank]])if(Number(amt)>0){await c.query(`INSERT INTO contract_payments(contract_id,amount,payment_date,payment_method,payment_type,comment,created_by,confirmed,confirmed_by,confirmed_at) VALUES(?,?,?,?,?,'[BALANCE_SOURCE_EXCLUDED] Импорт Google Sheets',?,1,?,CONCAT(?,' 12:00:00'))`,[id,amt,iso(x.date),method,/доп/i.test(x.action||'')?'additional':'initial',ADMIN,ADMIN,iso(x.date)]);payN++}await c.query(`INSERT INTO cash_register(office_id,entry_date,client_name,contract_number,action,lawyer_name,employee_id,cash_amount,noncash_amount,bank_amount,expense_amount,comment,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,[OFFICE,iso(x.date),x.client_name,x.contract_number,x.action||'Оплата',x.lawyer_raw,law.id,x.cash||0,x.noncash||0,x.bank||0,x.expense||0,'Импорт Google Sheets',ADMIN]);cashN++}
 await c.query(`UPDATE contracts c SET c.paid_amount=LEAST(c.amount,COALESCE((SELECT SUM(p.amount) FROM contract_payments p WHERE p.contract_id=c.id AND p.confirmed=1),0)),c.remainder_confirmed=CASE WHEN COALESCE((SELECT SUM(p.amount) FROM contract_payments p WHERE p.contract_id=c.id AND p.confirmed=1),0)>=c.amount AND c.amount>0 THEN 1 ELSE 0 END WHERE c.office_id=?`,[OFFICE]);
 let actN=0;for(const a of [...P.acts,...P.exceptions.unknown_acts]){const id=map.get(a.contract_number);if(!id)continue;const e=await employee(a.lawyer_raw||'Не указан');await c.query(`INSERT INTO acts(office_id,contract_id,act_date,amount,type,responsible_id,status,description,created_by,confirmed_at) VALUES(?,?,?,?,?,?,'confirmed',?,?,CONCAT(?,' 12:00:00'))`,[OFFICE,id,iso(a.date),a.amount||0,/представ/i.test(a.service||'')?'court_rep':'docs',e.id,`Импорт Google Sheets${a.representative?'; представитель: '+a.representative:''}`,ADMIN,iso(a.date)]);actN++}
 let repN=0;for(const r of [...P.representatives,...P.exceptions.unknown_representatives]){const id=map.get(r.contract_number);if(!id)continue;const e=await employee(r.representative||'Не указан','Представитель (исторический)');await c.query(`UPDATE contracts SET representative_id=?,description=CONCAT(COALESCE(description,''),'\nПредставитель: ',?,'; передача: ',?,'; заметки: ',?,'; статус: ',?) WHERE id=?`,[e.id,r.representative||'',r.handoff_date||'',r.notes||'',r.status||'',id]);repN++}
 let appN=0;for(const a of P.arrivals){const cid=await client(a.name,[]);const e=await employee(a.lawyer_raw||'Не указан');const result=/\+/.test(a.result||'')?'contract_signed':'not_signed';const rawt=String(a.time||'').replace(';',':');const mm=rawt.match(/^(\d{1,2}):(\d{2})/);const t=mm?String(mm[1]).padStart(2,'0')+':'+mm[2]+':00':'12:00:00';await c.query(`INSERT INTO appointments(office_id,client_id,client_name,client_phone,source,appointment_date,appointment_time,comment,operator_id,operator_name,status,consultation_result,manager_comment,is_technical,assigned_lawyer_id,created_at,updated_at) VALUES(?,?,?,?,'Импорт Google Sheets',?,?,?,?,?,'arrived',?,'Исторический импорт',0,?,CONCAT(?,' ',COALESCE(NULLIF(?,''),'12:00:00')),CONCAT(?,' ',COALESCE(NULLIF(?,''),'12:00:00')))`,[OFFICE,cid,a.name,'',iso(a.date),t,[a.topic,a.source,a.repeat_client].filter(Boolean).join(' | '),ADMIN,'Импорт',result,e.id,iso(a.date),t,iso(a.date),t]);appN++}
 let salN=0;for(const s of P.salary||[]){const e=await employee(s.name,'Сотрудник (исторический)');await c.query(`INSERT INTO salary_payments(office_id,employee_id,period_from,period_to,amount,payment_method,status,active_flag,calculation_snapshot,paid_by,paid_at,payment_date) VALUES(?,?,?,?,?,'noncash','paid',1,?,?,CONCAT(?,' 18:00:00'),?) ON DUPLICATE KEY UPDATE amount=salary_payments.amount+VALUES(amount),calculation_snapshot=VALUES(calculation_snapshot)`,[OFFICE,e.id,iso(s.period_from),iso(s.period_to),s.total,JSON.stringify({source:'Google Sheets',...s}),DIRECTOR,iso(s.period_to),iso(s.period_to)]);salN++}
 await c.query(`INSERT INTO office_balance_opening(office_id,start_date,opening_cash,opening_noncash,opening_bank,created_by) VALUES(?, '2024-03-11',0,0,0,?)`,[OFFICE,DIRECTOR]);const running={...zero};let finN=0;
 for(const d of P.daily_balance){for(const k of ['cash','noncash','bank']){const inc=Number(d.income[k]||0),exp=Number(d.expense[k]||0);if(inc){await c.query(`INSERT INTO office_income(office_id,income_date,payment_method,amount,title,description,created_by,source_type) VALUES(?,?,?,?,?,?,?,'google_balance_import')`,[OFFICE,d.date,k,inc,'Поступления по таблице','Сводная строка Google Sheets',ADMIN]);finN++}if(exp){await c.query(`INSERT INTO expenses(office_id,category,amount,expense_type,payment_method,is_auto,source_type,title,description,spent_on,created_by) VALUES(?,'Исторические расходы',?,'Разовый',?,0,'google_balance_import','Расходы по таблице',?,?,?)`,[OFFICE,exp,k,d.description||'Сводная строка Google Sheets',d.date,ADMIN]);finN++}running[k]+=inc-exp;const target=Number(d.closing[k]||0),diff=Math.round((target-running[k])*100)/100;if(diff>0){await c.query(`INSERT INTO office_income(office_id,income_date,payment_method,amount,title,description,created_by,source_type) VALUES(?,?,?,?,?,?,?,'google_balance_reconcile')`,[OFFICE,d.date,k,diff,'Сверка остатка','Автоматическая сверка с Google Sheets',ADMIN]);running[k]+=diff;finN++}else if(diff<0){await c.query(`INSERT INTO expenses(office_id,category,amount,expense_type,payment_method,is_auto,source_type,title,description,spent_on,created_by) VALUES(?,'Сверка остатка',?,'Разовый',?,0,'google_balance_reconcile','Сверка остатка','Автоматическая сверка с Google Sheets',?,?)`,[OFFICE,-diff,k,d.date,ADMIN]);running[k]+=diff;finN++}}}
 await c.commit();console.log(JSON.stringify({ok:true,contracts:contractN,clients:clients.size,payments:payN,cash:cashN,acts:actN,representatives:repN,appointments:appN,salary:salN,financial_rows:finN,running},null,2));
 }catch(e){try{await c.rollback()}catch{}throw e}finally{c.release()}}
main().then(()=>process.exit(0)).catch(e=>{console.error(e.stack||e);process.exit(1)});