const db=require('../db');
const ROLES=new Set(['director','manager','okk']);
const CATEGORIES=new Set(['LEAD_QUALITY','SALES_PROCESS','CLIENT_DELAY','SERVICE_PROBLEM','NON_TARGET','UNRESOLVED','OTHER']);
const REASON_CATEGORY={
 NEED_THINK:'CLIENT_DELAY',CONSULT_OTHERS:'CLIENT_DELAY',NOT_READY:'CLIENT_DELAY',RETURN_LATER:'CLIENT_DELAY',DELAY_OTHER:'CLIENT_DELAY',
 PRICE:'SERVICE_PROBLEM',NO_MONEY_NOW:'SERVICE_PROBLEM',PAYMENT_SCHEME:'SERVICE_PROBLEM',FINANCE_OTHER:'SERVICE_PROBLEM',CONDITIONS:'SERVICE_PROBLEM',SERVICE_SCOPE:'SERVICE_PROBLEM',VALUE_NOT_CLEAR:'SERVICE_PROBLEM',SOLUTION_REJECTED:'SERVICE_PROBLEM',
 NEED_NOT_IDENTIFIED:'SALES_PROCESS',SOLUTION_NOT_CLEAR:'SALES_PROCESS',VALUE_NOT_FORMED:'SALES_PROCESS',OBJECTION_NOT_HANDLED:'SALES_PROCESS',OFFER_NOT_MADE:'SALES_PROCESS',ARGUMENTS_INSUFFICIENT:'SALES_PROCESS',
 LOW_POTENTIAL:'LEAD_QUALITY',ECONOMICALLY_UNVIABLE:'LEAD_QUALITY',NO_SUPPORT_NEEDED:'LEAD_QUALITY',NOT_LEGALLY_SOLVABLE:'LEAD_QUALITY',
 NON_TARGET_SERVICE:'NON_TARGET',OUT_OF_PROFILE:'NON_TARGET',OTHER:'OTHER',INSUFFICIENT_DATA:'UNRESOLVED'
};
const FIELDS=['employee_id','source_id','topic','lead_quality','commercial_potential','service_fit','legally_solvable','need_identified','decision_maker_identified','solution_understood','offer_made','objection_identified','objection_processed','proposed_service','proposed_price','next_step','loss_category','loss_reason','manager_comment','evidence_sources','data_sufficiency','missing_data_reason','classification_basis','confidence_score'];
function bad(res,n,m){return res.status(n).json({success:false,message:m});}
function office(user){return Number(user.office_id);}
function manager(user){return ROLES.has(String(user.role||'').toLowerCase());}
function dates(q){const to=q.date_to||new Date().toISOString().slice(0,10);const d=new Date(to);d.setDate(d.getDate()-29);return [q.date_from||d.toISOString().slice(0,10),to];}
function valid(body){
 if(!REASON_CATEGORY[body.loss_reason]) return 'Выберите допустимую причину потери';
 if(!CATEGORIES.has(body.loss_category)) return 'Выберите основную категорию';
 if(REASON_CATEGORY[body.loss_reason]!==body.loss_category && !String(body.manager_comment||'').trim()) return 'При изменении основной категории нужен комментарий';
 if(body.data_sufficiency==='INSUFFICIENT'&&!String(body.missing_data_reason||'').trim()) return 'Укажите, каких данных недостаточно';
 if(body.loss_category==='SALES_PROCESS'&&!['NO','PARTIAL'].includes(body.need_identified)&&body.offer_made!=='NO'&&!['NO','PARTIAL'].includes(body.objection_processed)&&!String(body.manager_comment||'').trim()) return 'Для категории процесса продажи нужен подтверждающий признак или комментарий';
 return null;
}
async function appointment(id,user){const [r]=await db.query(`SELECT a.*,EXISTS(SELECT 1 FROM contracts c WHERE c.appointment_id=a.id) has_contract FROM appointments a WHERE a.id=? AND a.office_id=? LIMIT 1`,[id,office(user)]);return r[0];}
function payload(body,a,user){const o={};for(const f of FIELDS)o[f]=body[f]??null;o.employee_id=o.employee_id||a.assigned_lawyer_id||null;o.source_id=o.source_id||a.source_id||null;o.topic=o.topic||a.comment||null;o.evidence_sources=JSON.stringify(Array.isArray(body.evidence_sources)?body.evidence_sources:[]);o.confidence_score=Math.max(0,Math.min(100,Number(body.confidence_score)||0));o.updated_by=user.id;return o;}
const api={
 async getOne(req,res){try{if(!manager(req.user))return bad(res,403,'Нет доступа');const a=await appointment(req.params.consultationId,req.user);if(!a)return bad(res,404,'Консультация не найдена');const [r]=await db.query('SELECT * FROM consultation_analysis WHERE consultation_id=? AND deleted_at IS NULL',[a.id]);return res.json({success:true,data:r[0]||null,consultation:a});}catch(e){console.error(e);return bad(res,500,'Ошибка загрузки разбора');}},
 async upsert(req,res){const cx=await db.getClient();try{if(!manager(req.user))return bad(res,403,'Редактирование доступно только руководству');const a=await appointment(req.params.consultationId,req.user);if(!a)return bad(res,404,'Консультация не найдена');if(a.status!=='arrived'||a.consultation_result!=='not_signed'||Number(a.has_contract))return bad(res,400,'Разбор доступен только для состоявшейся консультации без договора');const er=valid(req.body);if(er)return bad(res,400,er);const data=payload(req.body,a,req.user);await cx.beginTransaction();const [rows]=await cx.query('SELECT * FROM consultation_analysis WHERE consultation_id=? FOR UPDATE',[a.id]);let row=rows[0];if(row){if(Number(req.body.version)!==Number(row.version)){await cx.rollback();return res.status(409).json({success:false,message:'Разбор уже изменён другим руководителем',data:row});}const set=FIELDS.map(f=>`${f}=?`).join(',');const vals=FIELDS.map(f=>data[f]);await cx.query(`UPDATE consultation_analysis SET ${set},updated_by=?,version=version+1,deleted_at=NULL,deleted_by=NULL WHERE id=?`,[...vals,req.user.id,row.id]);const [n]=await cx.query('SELECT * FROM consultation_analysis WHERE id=?',[row.id]);await cx.query(`INSERT INTO consultation_analysis_history(analysis_id,consultation_id,office_id,version,action,old_values,new_values,changed_by) VALUES (?,?,?,?,?,?,?,?)`,[row.id,a.id,a.office_id,n[0].version,'UPDATE',JSON.stringify(row),JSON.stringify(n[0]),req.user.id]);row=n[0];}else{const cols=['consultation_id','office_id',...FIELDS,'created_by','updated_by'];const vals=[a.id,a.office_id,...FIELDS.map(f=>data[f]),req.user.id,req.user.id];const [r]=await cx.query(`INSERT INTO consultation_analysis(${cols.join(',')}) VALUES (${cols.map(()=>'?').join(',')})`,vals);const [n]=await cx.query('SELECT * FROM consultation_analysis WHERE id=?',[r.insertId]);row=n[0];await cx.query(`INSERT INTO consultation_analysis_history(analysis_id,consultation_id,office_id,version,action,new_values,changed_by) VALUES (?,?,?,?,?,?,?)`,[row.id,a.id,a.office_id,1,'CREATE',JSON.stringify(row),req.user.id]);}await cx.commit();return res.json({success:true,data:row});}catch(e){try{await cx.rollback();}catch{}console.error(e);return bad(res,500,'Не удалось сохранить разбор');}finally{cx.release();}},
 async remove(req,res){const cx=await db.getClient();try{if(!manager(req.user))return bad(res,403,'Нет доступа');await cx.beginTransaction();const [r]=await cx.query('SELECT * FROM consultation_analysis WHERE consultation_id=? AND office_id=? AND deleted_at IS NULL FOR UPDATE',[req.params.consultationId,office(req.user)]);if(!r.length)return bad(res,404,'Разбор не найден');await cx.query('UPDATE consultation_analysis SET deleted_at=NOW(),deleted_by=?,updated_by=?,version=version+1 WHERE id=?',[req.user.id,req.user.id,r[0].id]);await cx.query(`INSERT INTO consultation_analysis_history(analysis_id,consultation_id,office_id,version,action,old_values,changed_by) VALUES (?,?,?,?,?,?,?)`,[r[0].id,r[0].consultation_id,r[0].office_id,r[0].version+1,'DELETE',JSON.stringify(r[0]),req.user.id]);await cx.commit();return res.json({success:true});}catch(e){try{await cx.rollback();}catch{}return bad(res,500,'Не удалось удалить разбор');}finally{cx.release();}},
 async summary(req,res){try{if(!manager(req.user))return bad(res,403,'Нет доступа');const [from,to]=dates(req.query),oid=office(req.user);const [[base]]=await db.query(`SELECT COUNT(*) arrived,SUM(a.consultation_result='contract_signed') contracts,SUM(a.consultation_result='not_signed') lost FROM appointments a WHERE a.office_id=? AND a.status='arrived' AND a.appointment_date BETWEEN ? AND ?`,[oid,from,to]);const [[s]]=await db.query(`SELECT COUNT(*) analyzed,SUM(lead_quality IN ('HIGH','MEDIUM')) promising,SUM(data_sufficiency='INSUFFICIENT') insufficient FROM consultation_analysis ca JOIN appointments a ON a.id=ca.consultation_id WHERE ca.office_id=? AND ca.deleted_at IS NULL AND a.appointment_date BETWEEN ? AND ?`,[oid,from,to]);const [cats]=await db.query(`SELECT loss_category category,COUNT(*) count FROM consultation_analysis ca JOIN appointments a ON a.id=ca.consultation_id WHERE ca.office_id=? AND ca.deleted_at IS NULL AND a.appointment_date BETWEEN ? AND ? GROUP BY loss_category`,[oid,from,to]);const arrived=Number(base.arrived||0),contracts=Number(base.contracts||0),promising=Number(s.promising||0);return res.json({success:true,data:{period:{from,to},arrived,contracts,lost:Number(base.lost||0),analyzed:Number(s.analyzed||0),coverage_pct:Number(base.lost)?Math.round(Number(s.analyzed||0)*10000/Number(base.lost))/100:0,promising,conversion_all_pct:arrived?Math.round(contracts*10000/arrived)/100:0,conversion_promising_pct:promising?Math.round(contracts*10000/promising)/100:0,insufficient:Number(s.insufficient||0),categories:cats}});}catch(e){console.error(e);return bad(res,500,'Ошибка аналитики');}},
 async details(req,res){try{if(!manager(req.user))return bad(res,403,'Нет доступа');const [from,to]=dates(req.query),limit=Math.min(Number(req.query.limit)||50,100),page=Math.max(Number(req.query.page)||1,1),params=[office(req.user),from,to];let filter='';if(req.query.category){filter=' AND ca.loss_category=?';params.push(req.query.category);}const [r]=await db.query(`SELECT ca.*,a.client_name,a.appointment_date,a.source,CONCAT(u.first_name,' ',u.last_name) employee_name FROM consultation_analysis ca JOIN appointments a ON a.id=ca.consultation_id LEFT JOIN users u ON u.id=ca.employee_id WHERE ca.office_id=? AND ca.deleted_at IS NULL AND a.appointment_date BETWEEN ? AND ?${filter} ORDER BY a.appointment_date DESC LIMIT ? OFFSET ?`,[...params,limit,(page-1)*limit]);return res.json({success:true,data:r,page,limit});}catch(e){return bad(res,500,'Ошибка детализации');}},
 async rankings(req,res){try{if(!manager(req.user))return bad(res,403,'Нет доступа');const [from,to]=dates(req.query),by=req.params.by==='employees'?'employee':'source';const col=by==='employee'?'ca.employee_id':'COALESCE(ca.source_id,0)',name=by==='employee'?"COALESCE(CONCAT(u.first_name,' ',u.last_name),'Не назначен')":"COALESCE(s.name,a.source,'Без источника')";const joins=by==='employee'?'LEFT JOIN users u ON u.id=ca.employee_id':'LEFT JOIN appointment_sources s ON s.id=ca.source_id';const [r]=await db.query(`SELECT ${col} id,${name} name,COUNT(*) analyzed,SUM(ca.lead_quality IN ('HIGH','MEDIUM')) promising,SUM(ca.loss_category='SALES_PROCESS') sales_losses FROM consultation_analysis ca JOIN appointments a ON a.id=ca.consultation_id ${joins} WHERE ca.office_id=? AND ca.deleted_at IS NULL AND a.appointment_date BETWEEN ? AND ? GROUP BY ${col},${name} ORDER BY promising DESC`,[office(req.user),from,to]);return res.json({success:true,data:r});}catch(e){console.error(e);return bad(res,500,'Ошибка рейтинга');}}
};
module.exports=api;
