const db=require('../db');
const {checkOfficeAccess}=require('../utils/ensureOffice');
const {employeeIdForUser}=require('../utils/employeeIdentity');
const {syncLegacyFields}=require('../services/installmentService');
const EDIT=new Set(['admin','administrator','director','manager','okk','lawyer']);
const round=v=>Math.round(Number(v||0)*100)/100;
async function access(req,connection=db){const[[c]]=await connection.query('SELECT id,office_id,id_employee,second_employee_id,amount,paid_amount,status FROM contracts WHERE id=?',[req.params.id]);if(!c)return{error:[404,'Договор не найден']};if(!await checkOfficeAccess(req.user,c.office_id))return{error:[403,'Доступ запрещён']};const role=String(req.user.role||'').toLowerCase();const eid=await employeeIdForUser(req.user.id,connection,c.office_id);if(!EDIT.has(role)||role==='lawyer'&&![Number(c.id_employee),Number(c.second_employee_id)].includes(Number(eid)))return{error:[403,'Нет права менять график доплат']};return{contract:c};}
exports.list=async(req,res)=>{try{const a=await access(req);if(a.error)return res.status(a.error[0]).json({success:false,message:a.error[1]});const[rows]=await db.query("SELECT id,amount,paid_amount,DATE_FORMAT(due_date,'%Y-%m-%d') due_date,status,note,created_at FROM contract_payment_installments WHERE contract_id=? AND status<>'cancelled' ORDER BY due_date,id",[a.contract.id]);res.json({success:true,data:rows,remaining_amount:round(a.contract.amount)-round(a.contract.paid_amount)});}catch(e){console.error('installments list',e);res.status(500).json({success:false,message:'Не удалось загрузить график доплат'});}};
exports.create=async(req,res)=>{const c=await db.getClient();try{await c.beginTransaction();const a=await access(req,c);if(a.error){await c.rollback();return res.status(a.error[0]).json({success:false,message:a.error[1]});}if(a.contract.status==='terminated')throw Object.assign(new Error('Договор расторгнут'),{status:409});const amount=round(req.body.amount),date=String(req.body.due_date||'').slice(0,10);if(amount<=0)throw Object.assign(new Error('Укажите сумму доплаты'),{status:400});if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date+'T00:00:00Z')))throw Object.assign(new Error('Укажите корректную дату'),{status:400});const[[planned]]=await c.query("SELECT COALESCE(SUM(amount-paid_amount),0) total FROM contract_payment_installments WHERE contract_id=? AND status IN ('pending','partial')",[a.contract.id]);const remaining=round(a.contract.amount)-round(a.contract.paid_amount);if(round(planned.total)+amount>remaining)throw Object.assign(new Error('Сумма графика превышает остаток по договору'),{status:400});const[r]=await c.query('INSERT INTO contract_payment_installments(contract_id,amount,due_date,note,created_by) VALUES(?,?,?,?,?)',[a.contract.id,amount,date,String(req.body.note||'').trim().slice(0,255)||null,req.user.id]);await syncLegacyFields(c,a.contract.id);await c.commit();res.status(201).json({success:true,data:{id:r.insertId,amount,due_date:date,status:'pending',paid_amount:0}});}catch(e){try{await c.rollback()}catch{};res.status(e.status||500).json({success:false,message:e.message||'Не удалось добавить доплату'});}finally{c.release();}};
exports.update=async(req,res)=>{const c=await db.getClient();try{await c.beginTransaction();const a=await access(req,c);if(a.error){await c.rollback();return res.status(a.error[0]).json({success:false,message:a.error[1]});}const[[row]]=await c.query("SELECT * FROM contract_payment_installments WHERE id=? AND contract_id=? AND status<>'cancelled' FOR UPDATE",[req.params.installmentId,a.contract.id]);if(!row)throw Object.assign(new Error('Доплата не найдена'),{status:404});const amount=round(req.body.amount),date=String(req.body.due_date||'').slice(0,10);if(amount<=0||amount<round(row.paid_amount))throw Object.assign(new Error('Сумма не может быть меньше уже оплаченной'),{status:400});if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Object.assign(new Error('Укажите корректную дату'),{status:400});const[[others]]=await c.query("SELECT COALESCE(SUM(amount-paid_amount),0) total FROM contract_payment_installments WHERE contract_id=? AND id<>? AND status IN ('pending','partial')",[a.contract.id,row.id]);const remaining=round(a.contract.amount)-round(a.contract.paid_amount);if(round(others.total)+round(amount-row.paid_amount)>remaining)throw Object.assign(new Error('Сумма графика превышает остаток по договору'),{status:400});const status=round(row.paid_amount)>=amount?'paid':round(row.paid_amount)>0?'partial':'pending';await c.query('UPDATE contract_payment_installments SET amount=?,due_date=?,note=?,status=? WHERE id=?',[amount,date,String(req.body.note||'').trim().slice(0,255)||null,status,row.id]);await syncLegacyFields(c,a.contract.id);await c.commit();res.json({success:true});}catch(e){try{await c.rollback()}catch{};res.status(e.status||500).json({success:false,message:e.message||'Не удалось изменить доплату'});}finally{c.release();}};
exports.remove=async(req,res)=>{const c=await db.getClient();try{await c.beginTransaction();const a=await access(req,c);if(a.error){await c.rollback();return res.status(a.error[0]).json({success:false,message:a.error[1]});}const[[row]]=await c.query("SELECT * FROM contract_payment_installments WHERE id=? AND contract_id=? FOR UPDATE",[req.params.installmentId,a.contract.id]);if(!row)throw Object.assign(new Error('Доплата не найдена'),{status:404});if(round(row.paid_amount)>0)throw Object.assign(new Error('Нельзя удалить частично оплаченную доплату'),{status:409});await c.query("UPDATE contract_payment_installments SET status='cancelled' WHERE id=?",[row.id]);await syncLegacyFields(c,a.contract.id);await c.commit();res.json({success:true});}catch(e){try{await c.rollback()}catch{};res.status(e.status||500).json({success:false,message:e.message||'Не удалось удалить доплату'});}finally{c.release();}};
